In [75]:
from modifiedMNIST import ModifiedMNIST
from torchvision import transforms
from torch.utils.data import DataLoader
from models import FullyConvolutionalNN
import torch

test_transform = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize((0.1307,), (0.3081,))
    ])

# create dataset
dataset = ModifiedMNIST(root='./data', train=True, download=True, transform=test_transform)
dl = DataLoader(dataset, batch_size=3, shuffle=True)

model = FullyConvolutionalNN(1, 10)

for x,y in dl:
    pred = model(x)
    pred = pred.argmax(dim=1)
    print(pred, len(pred))
    for i in range(len(pred)):
        unique_elements, counts = torch.unique(pred[i], return_counts=True)
        print(unique_elements, counts)
        sorted_indices = torch.argsort(counts, descending=True)
        print(unique_elements[sorted_indices[:2]])
        print(y)
    break

tensor([[[7, 7, 7, 8, 8, 7, 7],
         [7, 7, 5, 8, 8, 7, 7],
         [7, 7, 5, 5, 5, 7, 7],
         [7, 7, 5, 5, 8, 7, 7],
         [7, 7, 7, 7, 5, 7, 7],
         [7, 7, 7, 7, 5, 7, 7],
         [7, 7, 7, 5, 7, 7, 7]],

        [[7, 7, 7, 7, 7, 1, 8],
         [7, 7, 7, 7, 7, 5, 5],
         [7, 7, 7, 7, 5, 5, 7],
         [7, 7, 7, 7, 8, 8, 7],
         [7, 7, 7, 7, 7, 8, 7],
         [7, 7, 7, 7, 7, 5, 8],
         [7, 7, 7, 7, 5, 5, 7]],

        [[7, 7, 8, 8, 7, 7, 7],
         [7, 1, 5, 5, 7, 7, 7],
         [7, 7, 5, 7, 7, 7, 7],
         [7, 7, 8, 8, 7, 7, 7],
         [7, 7, 8, 8, 7, 7, 7],
         [7, 7, 1, 8, 7, 7, 7],
         [7, 7, 5, 5, 7, 7, 7]]]) 3
tensor([5, 7, 8]) tensor([ 9, 35,  5])
tensor([7, 5])
[tensor([5, 2, 9]), tensor([1, 3, 5])]
tensor([1, 5, 7, 8]) tensor([ 1,  7, 36,  5])
tensor([7, 5])
[tensor([5, 2, 9]), tensor([1, 3, 5])]
tensor([1, 5, 7, 8]) tensor([ 2,  5, 35,  7])
tensor([7, 8])
[tensor([5, 2, 9]), tensor([1, 3, 5])]
